- README.md
- package-lock.json
- sample.env
- src/core/payouts.ts
- src/core/sign.ts
- src/index.ts
cleaned up environment file
added more details to readme
added support for generation of ephemeral keys to process payout
closes https://github.com/jrwashburn/mina-pool-payout/issues/15
implements one potential solution for https://github.com/jrwashburn/mina-pool-payout/issues/12 
ephemeral keys would still require a manual transaction to fund and create the payout wallet - perhaps we should add the ability to generate the send-payment command for that transaction as well... and remember they will incur a 1m fee to create the account. may be worth it to not have to manage nonces and worry about key security.
> Ephemeral payout key

- src/core/payouts.ts
- src/index.ts
Closes #20.
The transactions are not generated, but the payout details are still saved for future querying.
It's worth noting that the handling of #10 already solved this problem in some cases as a side effect, since transactions won't be generated if there aren't any validated blocks. Doesn't hurt to have this protection in any case.
> Don't generate transactions with amount 0

- src/core/dataprovider-minaexplorer/block-queries-gql.ts
Looks like this should just be maxHeight? Tested this and works as expected e.g. `npm run payout -- -m=5000 -x=5150`
> Correcting maxHeight for GraphQL query

- README.md
- src/core/dataprovider-archivedb/block-queries-sql.ts
- src/core/dataprovider-archivedb/staking-ledger-json-file.ts
- src/core/dataprovider-minaexplorer/block-queries-gql.ts
- src/core/dataprovider-minaexplorer/staking-ledger-gql.ts
- src/core/payout-calculator.ts
- src/core/send-payments.ts
- src/index.ts
Cleans up data provider usage to simplify and eliminate database dependency when running against mina explorer.
Implements new features to redirect payments from one key to another key (support for sending awards due to a locked account to an unlocked account instead) and excluding keys from being paid at all (support for leaving pool owner funds alone and not paying them back to the pools delegators.)
Closes #33 and #34 
Still left to the pool owner to setup these redirects manually. In the future would prefer to have a signed message to auto-configure this.....
> 33 34 separate payout addresses

- README.md
- src/core/payout-calculator/payout-calculator-isolate-supercharge.ts
- src/core/payout-calculator/payout-calculator-original.ts
- src/core/send-payments.ts
- src/index.ts
removes supercharged weighting in favor of dedicated supercharge pool
new payout waterfall is:
First 720 coinbase - pro rata to all delegators
Fees - pro rata to all except O1/MF
Next 720 coinbase - pro rata to all unlocked accounts (unlocked at the given block height)
Ran and compared old and new algorithm for past epochs and results are equivalent with expected distribution changes.
Old algorithm can still be run by changing send-payment.ts and index.ts headers to include payout-calculator-original instead of payout-calculator-isolate-supercharge.
Files moved & renamed so the PR comparison is not useful; manually compare payout-calculator-original.ts to payout-calculator-isolate-supercharge.ts to see deltas.
> 58 supercharged handler update

- README.md
- sample.env
- src/core/payout-calculator/payout-calculator-isolate-supercharge.ts
- src/index.ts
Adds a new configuration parameter SEND_PAYOUT_THRESHOLD 
Will suppress payouts where the payout amount is less than OR EQUAL TO the specified configuration alue.
Value is specified in MINA, _not nanomina_.
Closes #55
> adding new config parameter SEND_PAYOUT_THRESHOLD to suppress tiny payments

- src/core/payment/PaymentBuilder.ts
Bug reported by Eddie B|FreshMina.
Running across epochs, unable to send transactions due to mismatched hash error.
Hash was never the same because of asynch behavior with data spanning epochs.
Resolved by adding a compound-key sort (block height + delegator public key).
Confirmed bug repro in main; confirmed bug free in branch.
Confirmed payout amounts are the same across main branch and this branch - as expected. Payment amounts were always correct; list order was causing different hashes to be generated.
Fringe benefit - hashes now reliably match across archive db and mina explorer data sources. This would allow even safer operation by using different data sources for the calculation vs. payout transmission runs.
> Sort transaction details so hash is always the same

- src/core/payment/PaymentProcessor.ts
Sorry about all the extra whitespace changes - line 37 is the only change - added await on isvalid. (I guess we could also change isvalid to not be async as another approach - it isn't doing anything but comparing vars.) Maybe that would be better? If you think that is better, please comment in review.
Unclear why some users get this error and others do not. Issue was reported by three separate pools:
https://discord.com/channels/484437221055922177/812415968101531708/881352968723648583
https://discord.com/channels/484437221055922177/799597981762453535/881626076890165348
https://discord.com/channels/484437221055922177/799597981762453535/881022813442543626
I could never reproduce, and neither could BeaconChain:
https://discord.com/channels/484437221055922177/799597981762453535/88178205132024 …
> await config validity

- src/core/payoutCalculator/PayoutCalculatorIsolateSuperCharge.ts
simple guard against incorrect ledger timing data or any other issue where supercharged amount is not 1440 as expected.
> adding check for supercharged amount

- src/configuration/ConfigurationManager.ts
Hello,
Here is a fix for the error "ERROR: Public Key is invalid at line N." that is encountered when using a ".negotiatedFees" file.
It just clean up .negotiatedFees empty rows.
> Fix error "ERROR: Public Key is invalid at line N."

- README.md
- src/resender.ts
- src/utils/resend-payment.ts
- src/utils/send-payments.ts
Separating sign transactions vs. send transactions to deal with intermittent node failures.
If an error occurs sending transactions, payout will stop trying to send and instead rapidly generate, sign, and store all remaining transactions for the run. Those transactions not sent can be re-transmitted manually using the resend command. (Details in readme.)
> Separate sign from send

- package.json
- src/core/payment/PaymentBuilder.ts
Prior code was throwing RangeError: Maximum call stack size exceeded because the expansion of the array when putting the detailed list exceeds stack size. Test case was array of ~130k items. Changed to for loop to manually copy in array. 
Better treatment would be to re-use the already populated array, but I didn't dig into that to trace what the impacts may be for this hot fix. 
Tested with large pool - confirmed resolved.
> handling >120k staker*blocks array

- src/core/payment/PaymentProcessor.ts
- src/core/transaction/TransactionProcessor.ts
Restoring prior functionality.
Due to pr 104/107 restructuring, total funds needed for payout was not available to log message. 
Moved log message to where the details are calculated. Not the cleanest, but will prevent breaking / support queries at the end of the epoch.
> fixup output messages to show mina to transfer helper text

- README.md
- package.json
- src/core/payment/SubstituteAndExcludePayToAddresses.ts
- src/core/payment/SubstituteAndExcludePayToAddressesForSuperCharge.ts
- src/core/transaction/TransactionBuilder.ts
Also, add csv-parse which seems to be missing from the dependencies.
We also reserialize the list of transactions since the SPLIT directive changes the objects in place and would cause havoc otherwise.
> support SPLIT in substitutePayTo

- README.md
- package.json
- sample.env
- src/core/payoutCalculator/PayoutCalculator.ts
- src/core/payoutCalculator/PayoutCalculatorIsolateSuperCharge.ts
- src/utils/staking-ledger-util.ts
Requested feature to allow pools to add more addresses to be treated as non-participating and burn their supercharged rewards.
Pools may have delegates whose tokens are locked by contract (not on-chain) who they need to exclude from supercharged rewards, and who would prefer to burn the supercharged portion of their coinbase in advance of the hard fork.
Added support for a new control file src/data/.burnSupercharged 
Any public keys found in the file will be treated as non-participating, and any supercharged portion of coinbase they generate will be burned.
The file does not need to be created if you don't have this scenario, and it is not in source control.
> add support for .burnSupercharged list; add to NPS and burn extra coinbase

- src/core/dataProvider/dataprovider-archivedb/block-queries-sql.ts
Don't need to check canonical blocks only to get min-max range; the block query will limit to canonical anyway.
> simplify block range query

- README.md
- src/configuration/ConfigurationManager.ts
- src/configuration/Model.ts
- src/core/payment/PaymentBuilder.ts
- src/core/payoutCalculator/Model.ts
- src/core/payoutCalculator/PayoutCalculator.ts
- src/core/payoutCalculator/PayoutCalculatorIsolateSuperCharge.ts
Implements an anonymous community request to burn a fractional amount of rewards that would otherwise be distributed for a key. Some pools have custom agreements to burn some of the award for certain delegates.
Supports a new control file - .negotiatedBurn, which may exist and should contain the public key and the burn percentage - one key per row.
> Implement variable rate burn for specific keys

- src/core/payment/PaymentBuilder.ts
- src/core/payment/SubstituteAndExcludePayToAddressesForSuperCharge.ts
- src/core/payoutCalculator/Model.ts
- src/core/payoutCalculator/PayoutCalculator.ts
- src/core/payoutCalculator/PayoutCalculatorIsolateSuperCharge.ts
- src/core/transaction/TransactionBuilder.ts
closes #126 
Adds ability to group payments to allow multiple payments to the same key (used to split MF burn transactions from .negotiatedBurn transactions.)
Will now always apply .negotiatedBurn
> Changes to .negotiatedBurn handling to always apply 

- .npmrc
- package.json
removing cross-fetch in favor of native fetch requires node versions >17.5; dev deps require 18.18.
Adding .npmrc and explicitly declaring node version dependency.
> make node version dependencies explicit

- .gitignore
- package.json
- src/core/payment/Model.ts
- src/core/payment/PaymentBuilder.ts
- src/core/payment/PaymentProcessor.ts
- src/core/payment/PaymentSummarizer.ts
- src/core/payment/Tests/PaymentBuilder.test.ts
- src/core/payment/Tests/PaymentSummarizer.test.ts
- src/core/payment/Tests/TransactionBuilder.test.ts
- src/core/payoutCalculator/Model.ts
- src/core/payoutCalculator/PayoutCalculator.ts
- src/core/payoutCalculator/PayoutCalculatorIsolateSuperCharge.ts
- src/core/transaction/TransactionBuilder.ts
- src/core/transaction/TransactionProcessor.ts
- src/core/transaction/TransactionSender.ts
Improve var names for clarity (payouts->payoutTransactions and storePayout->payoutDetails)
Add sort on payoutTransactions by amount desc - this sort standardizes sort order across data sources and returns to amount-sorted behavior in prior versions. (Requested by multiple operators.)
Consolidated hashing libs to just use node:crypto since it is already required for the MF memo, will now use same lib for the payout hash. 
Improved hash mismatch error to show different values.
> Sort results

- src/core/dataProvider/dataprovider-api/block-queries-api.ts
- src/core/payment/PaymentBuilder.ts
Include API endpoint URL in error messages.
Sort blocks when received from data provider to ensure rounding variations accumulate the same way.
Change payout transactions sort order to sort by amount then by public key so it is deterministic.
Now all data sources should result in the same hash for a given payout run.
> Compare-datasources

- README.md
- package.json
- sample.env
- src/configuration/ConfigurationManager.ts
- src/configuration/Model.ts
- src/core/payment/PaymentBuilder.ts
- src/core/payoutCalculator/Model.ts
- src/core/payoutCalculator/PayoutCalculatorFactory.ts
- src/core/payoutCalculator/PayoutCalculatorPostSuperChargeCommonShareFees.ts
- src/core/payoutCalculator/PayoutCalculatorPostSuperChargeKeepFees.ts
- src/core/payoutCalculator/PayoutCalculatorPostSuperChargeShareFees.ts
There are now 3 options for how fees are handled: shared among all stakers, shared exclusively by non-MF/O1/Investor stakers, or kept by the pool owner.
Pool owners can control this by setting new environment variable PAYOUT_CALCULATOR to postSuperChargeShareFees, postSuperChargeKeepFees, or postSuperChargeCommonShareFees.
> Allow user-specified payout calculator 
