- src/index.ts
output a sample ledger send-payment to fund the payour wallet
> Generate funding command

- src/index.ts
> 28 signed file missing fees

- README.md
- package-lock.json
- package.json
- sample.env
- src/core/graph-queries.ts
- src/core/queries.ts
- src/core/sign.ts
- src/index.ts
> 27 send payouts via graphql

- src/core/payouts.ts
Fixes #41 
Common shares now always pay pool commission rate
NPS shares always charged 0.05.
> common shares always pay whatever the pool commission rate is

- src/core/dataprovider-minaexplorer/block-queries-gql.ts
Casting explicitly when mapping it to Block type
> Changing minaExplorerbBlock to match the gpl Model.

- README.md
- src/core/dataprovider-archivedb/block-queries-sql.ts
- src/index.ts
Checks archive db for missing blocks or null parents
Contributed by @kobigurk 
Also adds (readme) reference to public data sources/endpoints for archive from piconbello and graphql proxy from beaconchain
> Validate archive integrity

- src/index.ts
Fixes #63 - Guilty of default values instead of throwing an exception, and not expecting a 0.0% pool fixed here and will throw exception instead.
> fixing (removing) default for commission rate

- src/core/transaction/TrasactionSender.ts
> Fix .paidblocks not found bug

- src/core/dataProvider/dataprovider-minaexplorer/staking-ledger-gql.ts
This limit needs to be increased to include all stakers
> Update limit for number of stakers

- src/composition/Types.ts
- src/composition/inversify.config.ts
- src/core/payment/Model.ts
- src/core/payment/PaymentBuilder.ts
- src/core/payment/PaymentProcessor.ts
- src/core/payment/PaymentSummarizer.ts
- src/core/payment/SubstituteAndExcludePayToAddresses.ts
- src/core/payment/SubstituteAndExcludePayToAddressesForSuperCharge.ts
- src/core/payment/Tests/PaymentSummarizer.test.ts
- src/core/payment/Tests/TransactionBuilder.test.ts
- src/core/transaction/Model.ts
- src/core/transaction/TransactionBuilder.ts
- src/core/transaction/TransactionProcessor.ts
- src/core/transaction/TrasactionSender.ts
Adding method to calculate totals and print to the console.
> #68 Calculate pool revenue & print

- src/core/payment/Model.ts
- src/core/payment/PaymentProcessor.ts
- src/core/payment/PaymentSummarizer.ts
fixes #77
it'd be nice to also output, say, an array of included epochs and ledgers, but i couldn't find that info available anywhere so, something for another day perhaps ;)
> write summary as json file alongside payout details and transactions

- src/core/dataProvider/dataprovider-minaexplorer/block-queries-gql.ts
Handling null for coinbasereceiver
> #79 handle null coinbasereceiver from mina explorer

- src/core/payoutCalculator/Model.ts
- src/core/payoutCalculator/PayoutCalculatorIsolateSuperCharge.ts
- src/core/transaction/TransactionBuilder.ts
Adds Mina alongside nanomina to console output from payout run per #76
> adding conversion from nanomina to mina for console.table

- src/configuration/ConfigurationManager.ts
- src/core/payoutCalculator/PayoutCalculator.ts
- src/core/payoutCalculator/PayoutCalculatorIsolateSuperCharge.ts
Fix for issue when commission rates from .negotiatedFees file is 0
> Fix when commissionRate from file is 0.

- src/core/dataProvider/dataprovider-minaexplorer/block-queries-gql.ts
Fixing path for .paiblocks in gql file
> Fixing paidblocks directory path

- README.md
- package.json
- src/resender.ts
- src/utils/resend-payment.ts
new resend command to send files previously generated where transactions were not broadcast.
> adding ability to resend saved payment .gql files

- sample.env
I thought this was already done, but keep seeing it pop up in discord - sorry!
> Remove minagraph

- src/core/dataProvider/dataprovider-api/staking-ledger-api.ts
Add `node-fetch` import to staking-ledger-api.ts
> Add `node-fetch` import to staking-ledger-api.ts

- src/index.ts
was printing out an outdated string for version. Now logging version from package.json.
> use version not hard coded string

- package.json
- src/core/dataProvider/dataprovider-minaexplorer/staking-ledger-gql.ts
Change calculation of sum of staking pool to use decimal.js to handle floating point numbers better.
> use decimal.js on mina explorer data provider to better handle float

- package.json
- src/core/dataProvider/dataprovider-api/block-queries-api.ts
for api data provider
add checks on http status and throw on api errors / log http error code to stdout.
> Add error handling for api / throw on http error

- package.json
minor update to package.json - newer dependencies, prune dependencies no longer used.
> clean up/update dependencies
